services:
  postgres:
    image: postgres:15
    container_name: postgres_orders
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: orders_service
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/orders_db?sslmode=disable
    ports:
      - "8080:8080"
      - "50051:50051"
      - "4000:4000"
    command: ["./main"]

volumes:
  postgres_data:
