

services:
  postgres:
    image: postgres:15
    container_name: postgres_orders
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations
    depends_on:
      - postgres
    entrypoint: [ "/bin/sh", "-c", "sleep 5 && migrate -path=/migrations -database 'postgres://user:password@postgres:5432/orders_db?sslmode=disable' up" ]


  app:
    build: .
    container_name: orders_service
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/orders_db?sslmode=disable
    ports:
      - "8080:8080"

volumes:
  postgres_data:



